name: pi5_gps_tracker
description: |
  Real-time GPS tracking app with live maps. 
  Track your location, view on interactive maps, and monitor movements in real-time.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  web_socket_channel: ^3.0.1
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon2.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21